steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: [
             'build',
             '-t', 'gcr.io/$PROJECT_ID/dbt-project:latest',
             '--build-arg', 'PROJECT_ID=$PROJECT_ID',
             '--build-arg', 'TAG_NAME=$TAG_NAME',
             '.'
         ]

images: ['gcr.io/$PROJECT_ID/dbt-project:latest']

